In [444]:
import math
def problem():
    L = [input()]
    c = 50
    h = 30
    q = math.sqrt((2*c*L))
    print(q)
    
problem()

1000


TypeError: unsupported operand type(s) for *: 'int' and 'dict'

In [383]:
import numpy as np
x = np.array(input())
y = np.array(input())
z = np.fromfunction(lambda x,y : x*y,(3,5))
print(z)

1,2,3,4,5
5,4,3,2,1
[[0. 0. 0. 0. 0.]
 [0. 1. 2. 3. 4.]
 [0. 2. 4. 6. 8.]]


In [392]:
l = input().split(',')
set(sorted(l))



without,hello,bag,world


{'bag', 'hello', 'without', 'world'}

In [398]:
l = input().split(' ')
set(sorted(l))


hello world and practice makes perfect and hello world again


{'again', 'and', 'hello', 'makes', 'perfect', 'practice', 'world'}

In [435]:
whitespace,alpha,string=0,0,"hello world! 123"
for i in string:
        
    if (i.isalpha()):
        alpha+=1
print("Number of Digit is", len(string)-(alpha))
print("Number of Alphabets is", alpha)


Number of Digit is 6
Number of Alphabets is 10


In [470]:
import re
l = []
items=[x for x in input().split(',')]
for i in items:
    if len(i)<6 and len(i)>12:
        continue
    else:
        pass
    if not re.search('[a-z]',i):
        continue
    elif not re.search('[A-Z]',i):
        continue
    elif not re.search('[0-9]',i):
        continue
    elif re.search('[$#@]',i):
        continue
    else:
        pass
    l.append(i)
print(''.join(l))
        
    

ABd1234@1, a F1#,2w3E*,2We3345
2w3E*2We3345
